# Generated by Django 5.2.16 on 2026-07-29 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistRevenueRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('unique_listener_count', models.PositiveBigIntegerField(default=0)),
                ('stream_count', models.PositiveBigIntegerField(default=0)),
                ('gross_revenue_cents', models.PositiveBigIntegerField(default=0)),
                ('platform_fee_cents', models.PositiveBigIntegerField(default=0)),
                ('net_revenue_cents', models.PositiveBigIntegerField(default=0, editable=False)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('IRR', 'Iranian Rial')], default='USD', max_length=3)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled')], db_index=True, default='pending', max_length=12)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('calculation_note', models.TextField(blank=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_records', to='artists.artistprofile')),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_artist_revenue_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start', 'artist__stage_name'],
                'indexes': [models.Index(fields=['payment_status', '-period_start'], name='revenue_status_period_idx'), models.Index(fields=['artist', '-period_start'], name='revenue_artist_period_idx')],
                'constraints': [models.UniqueConstraint(fields=('artist', 'period_start', 'period_end'), name='unique_artist_revenue_period'), models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='artist_revenue_valid_period'), models.CheckConstraint(condition=models.Q(('platform_fee_cents__lte', models.F('gross_revenue_cents'))), name='artist_revenue_fee_not_above_gross')],
            },
        ),
    ]
