# Generated by Django 5.2.16 on 2026-08-04 07:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('system', 'System'), ('artist', 'Artist'), ('billing', 'Billing'), ('support', 'Support'), ('playlist', 'Playlist')], max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('action_href', models.CharField(blank=True, max_length=500)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='notif_recipient_read_idx')],
            },
        ),
    ]
