# Generated by Django 5.2.16 on 2026-07-29 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('silver', 'Silver'), ('gold', 'Gold')], db_index=True, max_length=12, unique=True)),
                ('monthly_price_cents', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('IRR', 'Iranian Rial')], default='USD', max_length=3)),
                ('playlist_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('can_upload_profile_image', models.BooleanField(default=False)),
                ('can_download_tracks', models.BooleanField(default=False)),
                ('has_early_access', models.BooleanField(default=False)),
                ('can_view_advanced_stats', models.BooleanField(default=False)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_subscription_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['monthly_price_cents', 'tier'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_monthly_price_cents', models.PositiveBigIntegerField()),
                ('new_monthly_price_cents', models.PositiveBigIntegerField()),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_price_changes', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_changes', to='operations.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='subscriptionplan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('monthly_price_cents', 0), ('tier', 'basic')), models.Q(('monthly_price_cents__gt', 0), ('tier__in', ['silver', 'gold'])), _connector='OR'), name='subscription_plan_valid_price'),
        ),
        migrations.AddIndex(
            model_name='subscriptionpricechange',
            index=models.Index(fields=['plan', '-created_at'], name='price_change_plan_created_idx'),
        ),
    ]
