# Generated by Django 5.2.16 on 2026-08-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='artistsamplework',
            name='artist_sample_exactly_one_source',
        ),
        migrations.AddConstraint(
            model_name='artistsamplework',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('file__isnull', False), models.Q(('file', ''), _negated=True), ('external_url', '')), models.Q(models.Q(('file__isnull', True), ('file', ''), _connector='OR'), models.Q(('external_url', ''), _negated=True)), _connector='OR'), name='artist_sample_exactly_one_source'),
        ),
    ]
