# Generated by Django 5.2.16 on 2026-08-04 09:31

import django.db.models.deletion
import music.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0002_remove_artistsamplework_artist_sample_exactly_one_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=music.models.album_cover_upload_to)),
                ('release_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=12)),
                ('is_early_access', models.BooleanField(db_index=True, default=False)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='artists.artistprofile')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='music.genre')),
            ],
            options={
                'ordering': ['-release_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('audio_file', models.FileField(upload_to=music.models.track_audio_upload_to)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=music.models.track_cover_upload_to)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('lyrics', models.TextField(blank=True)),
                ('release_date', models.DateField()),
                ('track_number', models.PositiveSmallIntegerField(default=1)),
                ('explicit', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=12)),
                ('is_early_access', models.BooleanField(db_index=True, default=False)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='artists.artistprofile')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborative_tracks', to='artists.artistprofile')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='music.genre')),
            ],
            options={
                'ordering': ['album_id', 'track_number', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StreamEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100)),
                ('listened_seconds', models.PositiveIntegerField(default=0)),
                ('counted', models.BooleanField(db_index=True, default=False)),
                ('streamed_on', models.DateField(db_index=True)),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_events', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_events', to='music.track')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListeningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_played_at', models.DateTimeField()),
                ('play_count', models.PositiveIntegerField(default=1)),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_history', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='music.track')),
            ],
            options={
                'ordering': ['-last_played_at'],
            },
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['status', '-release_date'], name='album_status_release_idx'),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('artist', 'title', 'release_date'), name='unique_artist_album_release'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['status', '-release_date'], name='track_status_release_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['artist', '-release_date'], name='track_artist_release_idx'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(condition=models.Q(('album__isnull', False)), fields=('album', 'track_number'), name='unique_album_track_number'),
        ),
        migrations.AddIndex(
            model_name='streamevent',
            index=models.Index(fields=['listener', 'streamed_on', 'counted'], name='stream_listener_day_idx'),
        ),
        migrations.AddIndex(
            model_name='streamevent',
            index=models.Index(fields=['track', 'streamed_on', 'counted'], name='stream_track_day_idx'),
        ),
        migrations.AddConstraint(
            model_name='streamevent',
            constraint=models.UniqueConstraint(fields=('track', 'listener', 'session_id'), name='unique_track_listener_session'),
        ),
        migrations.AddConstraint(
            model_name='listeninghistory',
            constraint=models.UniqueConstraint(fields=('listener', 'track'), name='unique_listener_track_history'),
        ),
    ]
