# Generated by Django 5.2.16 on 2026-08-16 12:55

import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=music.models.album_cover_upload_to),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(max_length=500, upload_to=music.models.track_audio_upload_to),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=music.models.track_cover_upload_to),
        ),
    ]
